development:
  adapter: postgresql
  encoding: unicode
  database: imf/development
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: imf/development
  pool: 5
  username: 
  password: 